### ISSUE TITLE
AirFire without flags [question]

### ISSUE THREAD

**Issue by freakexeuLow** [ExtendedPlugs/AirFire#1]
Hey :)
I'm looking for such a plugin, but I want it without flags. Is it possible to determine this yourself?

**Comment by whyAries** [comment]
@freakexeuLow Try `dd_flag ""`

**Comment by freakexeuLow** [comment]
> 
> 
> @freakexeuLow Try `dd_flag ""`

sorry, i read only this here on github "Working only for clients with flag" but i translate the text on hlmod and read: Flags: Give access to all - leave empty flag kvar.

It works, thanks anyway for the info :)
